spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.69.22.7:1521:orcl
    username: bph_qwgl
    password: bph_qwgl
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.founder.job.entity
server:
  port: 10409


