package com.founder.job.dao;

import com.founder.job.entity.RfWaterMark;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface RfWaterMarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCJ_CONF_SCHEDULER
     *
     * @mbg.generated
     */
    int insert(RfWaterMark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCJ_CONF_SCHEDULER
     *
     * @mbg.generated
     */
    int insertSelective(RfWaterMark record);

    List<RfWaterMark> queryApis();

}